from rest_framework.routers import SimpleRouter
from app_telegram.views.search_views import RoomSearchView, MessageSearchView, MessagesEmbedSearchView
from app_telegram.views.staff_views import TelegramAuthView, SeedView, RoomView, MessageView


telegram_router = SimpleRouter(trailing_slash=False)
# New router to avoid collisions with the endpoints generated by `django_elasticsearch_dsl_drf` 
# need to be added to the urls.py after the `telegram_router` 
telegram_search_router = SimpleRouter(trailing_slash=False)

# `telegram_auth` endpoints.
telegram_router.register(r'auth', TelegramAuthView, basename='tgauth')

# 'seed' endpoints.
telegram_router.register(r'seed', SeedView, basename='seed-staff')

# 'room' endpoints.
telegram_router.register(r'room', RoomView, basename='room-staff')
telegram_search_router.register(r'room/search', RoomSearchView, basename='room-search')

# 'message' endpoints.
telegram_router.register(r'msg', MessageView, basename='msg-staff')
telegram_router.register(r'msg', MessagesEmbedSearchView, basename='msg-search-ai') # no colision with MessageSearchView 
telegram_search_router.register(r'msg/search', MessageSearchView, basename='msg-search')